# Generated by Django 4.1.5 on 2023-01-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='earned',
        ),
    ]
